-- 1. Crear tabla de Roles
create table public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  web_access boolean default false,
  mobile_access boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Insertar roles iniciales (Ejemplos)
insert into public.roles (name, web_access, mobile_access) values
('Administrador', true, true),
('Analista de Gestión', true, false),
('Supervisor', true, true),
('Operario', false, true);

-- 3. Modificar tabla employees para vincular con roles
-- Nota: Si ya tienes datos, podrías necesitar una migración más cuidadosa
alter table public.employees 
add column role_id bigint references public.roles(id);

-- 4. (Opcional) Migrar roles existentes si usabas un campo de texto
-- update public.employees set role_id = (select id from public.roles where name = 'Administrador') where role = 'ADMIN';

-- 5. Crear políticas de seguridad (RLS) si es necesario
alter table public.roles enable row level security;

create policy "Roles visibles para todos los autenticados"
  on public.roles for select
  to authenticated
  using (true);

create policy "Solo administradores pueden editar roles"
  on public.roles for all
  to authenticated
  using (
    exists (
      select 1 from public.employees e
      join public.roles r on e.role_id = r.id
      where e.id = auth.uid() and r.name = 'Administrador'
    )
  );
